config/routes.rb
JotCssReport::Application.routes.draw do
  
  root 'static_pages#home'
  match '/create', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin' , to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  resources :reports
  resources :users
  resources :equipment
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :reports
	validates :serial, uniqueness: { case_sensetive: false}

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.paginate(page: params[:page])
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @equipment }
      else
        format.html { render action: 'new' }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:jcode, :serial, :mdate, :pnumber)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "You are not Authorized!"
      end
    end

    def correct_user
    @user = User.find(params[:id])
    redirect_to (root_url) unless current_user?(@user)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jcode, "J-Code" %><br>
    <%= f.text_field :jcode %>
  </div>
  <div class="field">
    <%= f.label :serial, "Serial Number" %><br>
    <%= f.number_field :serial %>
  </div>
  <div class="field">
    <%= f.label :mdate, "Manufacturing Date" %><br>
    <%= f.date_select :mdate %>
  </div>
  <div class="field">
    <%= f.label :pnumber, "Project Number" %><br>
    <%= f.text_field :pnumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<% provide(:title,'Edit Equipment information')%>
<% provide(:name,'Edit Equipment information')%>

	<p>
	<%= link_to 'Show', @equipment %> |
	<%= link_to 'Back', equipment_index_path %>
	</p>

<%= render 'form' %>

app/views/equipment/index.html.erb
<% provide(:title,'List of Equipment')%>
<% provide(:name,'List of JOT Equipment')%>

	<p>
  <%= link_to "Crate New Equipment ", new_equipment_path %>
</p>

<%= will_paginate %>

<table width="930", border="1">
  <thead>
    <tr>
      <th>J-Code</th>
      <th>Serial number</th>
      <th>Date</th>
      <th>Project number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= equipment.jcode %></td>
        <td><%= equipment.serial %></td>
        <td><%= equipment.mdate %></td>
        <td><%= equipment.pnumber %></td>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>

<%= will_paginate %>

app/views/equipment/new.html.erb
<%provide(:title,'New Eqipment')%>
<%provide(:name,'Create new Equipment')%>


	<p>
	<%= link_to 'Back', equipment_index_path %>
	</p>

	<%= render 'form' %>

app/views/equipment/show.html.erb
<%provide(:title,'Equipment information')%>
<%provide(:name,'Equipment information')%>


<p>
  <%= link_to 'Edit', edit_equipment_path %> |
  <%= link_to 'Back', equipment_index_path %> |
  <%= link_to 'New Report', new_report_path %>
</p>

<table width="600", border="1">
  <tr>
    <td width="130"><strong>Equipment ID</strong></td>
    <td width="470"><%= @equipment.id%></td>
  </tr>

  <tr>
    <td width="130"><strong>J-Code:</strong></td>
    <td width="470"><%= @equipment.jcode %></td>
  </tr>

  <tr>
    <td width="130"><strong>Serial Number:</strong></td>
    <td width="470"><%= @equipment.serial %></td>
  </tr>

  <tr>
    <td width="130"><strong>Manufacturing Date:</strong></td>
    <td width="470"><%= @equipment.mdate %></td>
  </tr>

  <tr>
    <td width="130"><strong>Project Number:</strong></td>
    <td width="470"><%= @equipment.pnumber %></td>
  </tr>
</table>