config/routes.rb
JotCssReport::Application.routes.draw do
  
  root 'static_pages#home'
  match '/create', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin' , to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  resources :reports
  resources :users
  resources :equipment
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :equipment
end

app/models/reports.rb
class Reports < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.paginate(page: params[:page])
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:equipment_id, :subject, :sdate, :fdate, :rname, :location, :cname, :description, :status)
    end

   def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "You are not Authorized!"
      end
    end
    
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equipment_id, "Equipment ID" %><br>
    <%= f.number_field :equipment_id %>
  </div>
  <div class="field">
    <%= f.label :subject, "Subject" %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :sdate, "Problem appears" %><br>
    <%= f.date_select :sdate %>
  </div>
  <div>
    <%= f.time_select :sdate %>
  </div>

  <div class="field">
    <%= f.label :fdate, "Problem resolved" %><br>
    <%= f.date_select :fdate %>
  </div>
  <div>
    <%= f.time_select :fdate %>
  </div>
  <div class="field">
    <%= f.label :rname, "Reporter Name" %><br>
    <%= f.text_field :rname %>
  </div>
  <div class="field">
    <%= f.label :location, "Location" %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :cname, "Customer" %><br>
    <%= f.text_field :cname %>
  </div>
  <div class="field">
    <%= f.label :description, "Description" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status, "Status" %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<% provide(:title,'Edit Report')%>
<% provide(:name, 'Edit Report')%>



<p>
	<%= link_to 'Show' , @report %> |
	<%= link_to 'Back', reports_path %>
</p>

<%= render 'form' %>

app/views/reports/index.html.erb
<% provide(:title,'List of reports')%>
<% provide(:name,'List of incident reports')%>

  <p>
  <%= link_to 'Create New Report', new_report_path %>
</p>

<%= will_paginate %>

<table width="930" border="1">
  <thead>
    <tr>
      <th>Equipment ID</th>
      <th>Subject</th>
      <th>Incident start</th>
      <th>Reporter name</th>
      <th>Location</th>
      <th>Customer</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.equipment_id %></td>
        <td><%= report.subject %></td>
        <td><%= report.sdate %></td>
        <td><%= report.rname %></td>
        <td><%= report.location %></td>
        <td><%= report.cname %></td>
        <td><%= report.status %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate %>

app/views/reports/new.html.erb
<% provide(:title, 'New Report')%>
<% provide(:name,'New Incident Report')%>


<p>
	<%= link_to 'Back', reports_path %>
</p>

<%= render 'form' %>

app/views/reports/show.html.erb
<% provide(:title, 'Report')%>
<% provide(:name,'Report information')%>


<p>
  <%= link_to 'Edit', edit_report_path(@report) %> |
  <%= link_to 'Back', reports_path %>
</p>

<table width="600", border="1">

    <tr>
      <td width="140"><strong>Equipment ID:</strong></td>
      <td width="460"><strong><%= @report.equipment_id%></strong></td>
    </tr>

    <tr>
      <td width="140"><strong>Subject:</strong></td>
      <td width="460"><%= @report.subject %></td>
    </tr>

    <tr>
      <td width="140"><strong>Incident start:</strong></td>
      <td width="460"><%= @report.sdate %></td>
    </tr>

    <tr>
      <td width="140"><strong>Incident resolved:</strong></td>
      <td width="460"><%= @report.fdate %></td>
    </tr>

    <tr>
      <td width="140"><strong>Reporter name:</strong></td>
      <td width="460"><%= @report.rname %></td>
    </tr>

    <tr>
      <td width="140"><strong>Location:</strong></td>
      <td width="460"><%= @report.location %></td>
    </tr>

    <tr>
      <td width="140"><strong>Customer</strong></td>
      <td width="460"><%= @report.cname %></td>
    </tr>

    <tr>
      <td width="140"><strong>Description:</strong></td>
      <td width="460"><%= @report.description %></td>
    </tr>

    <tr>
      <td width="140"><strong>Status:</strong></td>
      <td width="460"><%= @report.status %></td>
    </tr>
</table>