config/routes.rb
JotCssReport::Application.routes.draw do
  
  root 'static_pages#home'
  match '/create', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin' , to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  resources :reports
  resources :users
  resources :equipment
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	<strong>Jot Customer service report</strong>
  	by Pavel Svirida
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://jotautomation.com">Jot News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="jot-bar">
        <div class="container">
          <img id = "logo" src="http://www.jotautomation.com/media/layout/logo.png" alt="JOT">
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path, style: 'color: #FFFFFF' %></li>
              <% if signed_in? %>
              <li><%= link_to "Equipments", equipment_index_path, style: 'color: #FFFFFF' %></li>
              <li><%= link_to "Reports", reports_path, style: 'color: #FFFFFF' %></li>
              <li>
                <%= link_to "Users", users_path, style: 'color: #FFFFFF' %>
              </li>
              <li id="fat-menu" class="dropdown">
                <a href="#"  style="color: #FFFFFF" class="dropdown-toogle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li> <%= link_to "View Profile", current_user %></li>
                  <li> <%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                  <li class="divider">
                    <li>
                      <%= link_to "Sign out", signout_path, methode: "delete" %>
                    </li>
                  </li>
                </ul>
              </li>

              <% else %>
              <li><%= link_to "Sign in", signin_path, style: 'color: #FFFFFF' %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/_test.html.erb
<header class="jot-bar">
	<img id = "logo" src="http://www.jotautomation.com/media/layout/logo.png" alt="JOT">
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>

  <body>
    
    <%= render '/layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"> <%= value %></div>
      <% end %>
      <%= yield %>
      <%= render '/layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

   
  </body>


</html>